build:
  version: "4.5.264"

info:
  message: "Welcome to EazyBank cards related loacal-dev APIs "
  contactDetails:
    name: "Cherryl Pankaj - QA Lead"
    email: "cherryl@eazybank.com"
  onCallSupport:
    - (310) 875-4367
    - (201) 236-1267
