build:
  version: "4.5.260"
server:
  port: 9550
info:
  message: "Welcome to Bank related QA APIs "
  contactDetails:
    name: "Cherryl Pankaj - QA Lead"
    email: "cherryl@eazybank.com"
  onCallSupport:
    - (310) 875-4367
    - (201) 236-1267
